config/routes.rb
Airbyob::Application.routes.draw do
  root to: "static_pages#root"

  resources :users do
    resources :sites, :only => [:new, :create]
    match 'owned_sites', to: 'sites#owned', via: :get
  end

  resources :sites, :except => [:new, :create]
  resource :session, :only => [:new, :create, :destroy]
end

app/models/site.rb
class Site < ActiveRecord::Base
  validates :title, :description, :location, :price, :size, :presence => true

  belongs_to(
    :owner,
    :foreign_key => :user_id,
    :class_name => "User"
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  before_validation :ensure_session_token
  validates :username, :email, :presence => true, :uniqueness => true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :password_digest, :session_token, :presence => true

  has_many :sites

  def self.generate_token
    SecureRandom::urlsafe_base64(24)
  end

  def self.find_by_credentials(login_params)
    user = User.find_by_username(login_params[:username])

    if user && user.is_password?(login_params[:password])
      user
    else
      nil
    end
  end

  def password=(plaintext)
    @password = plaintext
    self.password_digest = BCrypt::Password.create(plaintext)
  end

  def is_password?(plaintext)
    BCrypt::Password.new(self.password_digest).is_password?(plaintext)
  end

  def reset_session_token!
    self.session_token = self.class.generate_token
    self.save

    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_credentials(login_params)

    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["invalid username or password"]
      render :new
    end
  end

  def destroy
    logout!

    redirect_to new_session_url
  end

  def new
    @user = User.new

    render :new
  end

  private

  def login_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :verify_owner, :only => [:edit, :update, :destroy]

  def create
    @site = current_user.sites.new(site_params)

    if @site.save
      redirect_to site_url(@site)
    else
      flash.now[:errors] = @site.errors.full_messages
      render :new
    end
  end

  def destroy
    @site = Site.find(params[:id])

    if current_user.is_password?(params[:user][:password])
      @site.destroy

      redirect_to user_owned_sites_url(current_user)
    else
      flash.now[:errors] = ["incorrect password"]
      render :edit
    end
  end

  def edit
    @site = Site.find(params[:id])

    render :edit
  end

  def index
    @sites = Site.all

    render :index
  end

  def new
    @site = Site.new

    render :new
  end

  def owned
    @user = User.find(params[:user_id])
    @sites = @user.sites

    render :owned
  end

  def update
    @site = Site.find(params[:id])

    if @site.update(site_params)
      redirect_to site_url(@site)
    else
      flash.now[:errors] = @site.errors.full_messages
      render :edit
    end
  end

  def show
    @site = Site.find(params[:id])
    @owner = @site.owner

    render :show
  end

  private

  def site_params
    params.require(:site).permit(:title, :description, :location, :size, :price)
  end

  def verify_owner
    site = Site.find(params[:id])
    accessed_user = site.owner
    redirect_to root_url unless current_user == accessed_user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
    render :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_user, :only => [:edit, :update, :destroy]

  def create
    @user = User.new(user_params)

    if password_confirmed?
      if @user.save
        login!(@user)
        redirect_to user_url(@user)
      else
        flash.now[:errors] = @user.errors.full_messages
        render :new
      end
    else
      flash.now[:errors] = ["password and confirmation do not match"]
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.is_password?(params[:user][:password])
      @user.destroy

      redirect_to new_user_url
    else
      flash.now[:errors] = ["incorrect password"]
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])

    render :edit
  end

  def new
    @user = User.new

    render :new
  end

  def show
    @user = User.find(params[:id])

    render :show
  end

  def update
    @user = User.find(params[:id])

    if @user.is_password?(params[:user][:password])
      if @user.update(user_params)
        redirect_to user_url(@user)
      else
        flash.now[:errors] = @user.errors.full_messages
        render :edit
      end
    else
      flash.now[:errors] = ["incorrect password"]
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def password_confirmed?
    params[:user][:password] == params[:user][:password_confirmation]
  end

  def verify_user
    user = User.find(params[:id])
    redirect_to user_url(current_user) unless current_user == user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login!(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_url %>">AirBYOB</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Where to?">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">...Nothing here yet</a></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="<%= user_owned_sites_url(current_user) %>">Your Land</a></li>
              <li><a href="<%= edit_user_url(current_user) %>">Edit Profile</a></li>

              <li class="divider"></li>
              <li><%= button_to "Log Out", session_url, :method => :delete,
                :class => "btn btn-link" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_url %></li>
          <li><%= link_to "Log In", new_session_url %></li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Help <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">...Nothing here yet</a></li>
          </ul>
        </li>
        <li>
          <%= button_to "List Your Land",
              (current_user && new_user_site_url(current_user)) || new_session_url,
              :method => :get, :class => "btn navbar-btn btn-warning btn-sm" %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirBYOB</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <%= yield %>

</body>
</html>

app/views/sites/_form.html.erb
<% form_action = action == :new ? user_sites_url(user) : site_url(site) %>
<% form_method = action == :new ? 'POST' : 'PATCH' %>
<% form_submit = action == :new ? 'List Land' : 'Update Details' %>


<form action="<%= form_action %>" method="post" accept-charset="utf-8">
  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>" id="authenticity_token">

  <input type="hidden" name="_method" value="<%= form_method %>" id="_method">

  <label for="title">Title</label>
  <input type="text" name="site[title]" value="<%= site.title %>" id="title">

  <label for="description">Description</label>
  <input type="text" name="site[description]" value="<%= site.description %>" id="description">

  <label for="location">Location</label>
  <input type="text" name="site[location]" value="<%= site.location %>" id="location">

  <label for="price">Price</label>
  <input type="text" name="site[price]" value="<%= site.price %>" id="price">

  <label for="size">Size</label>
  <select name="site[size]" id="size">
    <option value="1">&lt; 0.5 acres</option>
    <option value="2">&lt; 1 acre</option>
    <option value="3">&lt; 5 acres</option>
    <option value="4">&lt; 10 acres</option>
    <option value="5">&gt; 10 acres</option>
  </select>

  <p><input type="submit" value="<%= form_submit %>"></p>
</form>

<% if action == :edit %>
  <hr>
  <form action="<%= site_url(site) %>" method="post" accept-charset="utf-8">
    <input type="hidden" name="authenticity_token"
           value="<%= form_authenticity_token %>" id="authenticity_token">

    <input type="hidden" name="_method" value="delete" id="_method">

    <label for="password">Confirm Password</label>
    <input type="password" name="user[password]" id="password">

    <p><input type="submit" value="Delete Listing"></p>
  </form>
<% end %>

app/views/sites/edit.html.erb
<div class="container">
  <h1>Update Site Details</h1>

  <%= render 'form', :site => @site, :user => current_user, :action => :edit %>
</div>

app/views/sites/index.html.erb
<div class="container">
  <h1>Sites</h1>

  <%= @sites.to_json %>
</div>

app/views/sites/new.html.erb
<div class="container">
  <h1>List Your Land</h1>

  <%= render 'form', :site => @site, :user => current_user, :action => :new %>
</div>

app/views/sites/owned.html.erb
<div class="container">
  <h1><%= @user.username %>'s Properties</h1>

  <ul>
    <% @sites.each do |site| %>
      <li>
        <%= link_to site.title, site_url(site) %>
        <% if @user == current_user %>
          <%= link_to "Edit", edit_site_url(site), :class => "btn btn-default btn-xs" %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/sites/show.html.erb
<div class="container">
  <h1><%= @site.title%></h1>
  <h4><%= @site.location %></h4>
  <div class="row">

    <div class="col-xs-8">
      <div class="site-pictures">
        <!-- TODO: placeholder -->
        <img class="site-picture" src="http://upload.wikimedia.org/wikipedia/commons/e/e1/Gocsej_village_house_backyard.jpg">
      </div>

      <div class="site-info">
        <ul class="nav nav-tabs">
          <li class="active">
            <a href="#description" data-toggle="tab">Description</a>
          </li>
          <li>
            <a href="#amenities" data-toggle="tab">Amenities</a>
          </li>
        </ul>

        <div class="tab-content">
          <div class="tab-pane active" id="description">
            <p><%= @site.description %></p>
          </div>
          <div class="tab-pane" id="amenities">...</div>
        </div>

      </div>
    </div>

    <div class="col-xs-4">
      <div class="well">
        From: $<%= @site.price %>
        <%= link_to "Book It", "#", :class => "btn btn-primary book-btn"%>
      </div>

      <div class="well">
        <%= button_to "Save to Wishlist", "#", :class => "btn btn-default fav-btn"%>
      </div>

      <div class="well owner-info">
        <!-- TODO: placeholder -->
        <img class="owner-picture" src="http://upload.wikimedia.org/wikipedia/commons/2/27/Sherman_Profile.png">

        <%= link_to @owner.username, user_url(@owner), :class => "owner-link" %>

        <%= link_to "Contact Me", "#", :class => "btn btn-default contact-btn" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_carousel.html.erb
<div id="carousel-airbyob" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-airbyob" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-airbyob" data-slide-to="1"></li>
    <li data-target="#carousel-airbyob" data-slide-to="2"></li>
    <li data-target="#carousel-airbyob" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="http://placekitten.com/1575/497">
      <div class="carousel-caption">
        dat cat
      </div>
    </div>
    <div class="item">
      <img src="http://placekitten.com/1576/501">
      <div class="carousel-caption">
        is so fat
      </div>
    </div>
    <div class="item">
      <img src="http://placekitten.com/1574/501">
      <div class="carousel-caption">
        y u so fat
      </div>
    </div>
    <div class="item">
      <img src="http://placekitten.com/1577/504">
      <div class="carousel-caption">
        mr cat?
      </div>
    </div>

  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-airbyob" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-airbyob" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

app/views/static_pages/root.html.erb
<div id="root-container">
<%= render 'carousel' %>

  <form action="#" method="get" accept-charset="utf-8" id="root-search-form" class="row gray-well">
    <input type="text" name="some_name" value="" id="some_name" class="form-control-inline">
    <input type="text" name="some_name" value="" id="some_name" class="form-control-inline">
    <input type="submit" value="Search" class="btn btn-info btn-xs btn-root-form">
  </form>
</div>

app/views/users/_form.html.erb
<% form_action = action == :new ? users_url : user_url(user) %>
<% form_method = action == :new ? 'POST' : 'PATCH' %>
<% form_submit = action == :new ? 'Sign Up' : 'Update Info' %>
<% form_password = action == :new ? 'Password' : 'Confirm Password' %>


<form action="<%= form_action %>" method="post" accept-charset="utf-8">
  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>" id="authenticity_token">

  <input type="hidden" name="_method" value="<%= form_method %>" id="_method">

  <label for="username">Username</label>
  <input type="text" name="user[username]" value="<%= user.username %>" id="username">

  <label for="email">Email</label>
  <input type="text" name="user[email]" value="<%= user.email %>" id="email">

  <label for="password"><%= form_password %></label>
  <input type="password" name="user[password]" id="password">

  <% if action == :new %>
    <label for="password_confirmation">Password Confirmation</label>
    <input type="password" name="user[password_confirmation]" id="password_confirmation">
  <% end%>

  <p><input type="submit" value="<%= form_submit %>"></p>
</form>

<% if action == :edit %>
  <hr>
  <form action="<%= user_url(user) %>" method="post" accept-charset="utf-8">
    <input type="hidden" name="authenticity_token"
           value="<%= form_authenticity_token %>" id="authenticity_token">

    <input type="hidden" name="_method" value="delete" id="_method">

    <label for="password"><%= form_password %></label>
    <input type="password" name="user[password]" id="password">

    <p><input type="submit" value="Delete My Account"></p>
  </form>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h1>Update Profile</h1>

  <%= render 'form', :user => @user, :action => :edit %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign Up</h1>

  <%= render 'form', :user => @user, :action => :new %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1><%= @user.username %></h1>

</div>